services:
  - type: web
    name: event-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn event_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: event-manager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: event-manager-db
    plan: free